### ISSUE TITLE
STOP_MARKET order need trigger_price

### ISSUE THREAD

**Issue by pomor** [rundef/async_rithmic#1]
```
 if order_type in [OrderType.STOP_MARKET]:
            if "trigger_price" not in kwargs:
                raise Exception("Price must be specified for this target order price")
            msg_kwargs["trigger_price"] = kwargs["trigger_price"]
```

**Comment by rundef** [comment]
hey, thanks for reporting, I don't really use STOP orders so this bug fell through the cracks

this has been fixed in this commit https://github.com/rundef/async_rithmic/commit/77f4c8b5fc8307e033855d466e6a75662d302cd6 and released in v1.2.6

**Comment by dominiontrading** [comment]
Ah, was curious if this library supported StopMarket orders - rundef, I'm the author of the original pyrithmic, your library looks awesome! Is anyone using this for live trading? I'm keen to use this for live within the next two weeks, will be trying out with my paper trading account. Is there anything I can do to help support the project?

**Comment by rundef** [comment]
> Ah, was curious if this library supported StopMarket orders - rundef, I'm the author of the original pyrithmic, your library looks awesome! Is anyone using this for live trading? I'm keen to use this for live within the next two weeks, will be trying out with my paper trading account. Is there anything I can do to help support the project?

Hi! thanks for the kind word, means a lot coming from the original pyrithmic author 🙏
Yes, there are users using it in prod, but ofc you should experiment with a paper trading account first.
Feel free to report any issue you run into (bugs, rough edges, missing features or even just confusing parts of the API ), that would be super valuable.

**Comment by dominiontrading** [comment]
Stuck trying to get my paper account access fixed arggh, bloody Rithmic..anyways, just wondering if the library does any intelligent reporting back of linking up the child orders of a bracket order, don't know if there's anywhere to see what this looks like (obviously will be able to when I can paper trade again) in documentation? Also, whether the order_id I give the parent order, lets say fancy_order_123, which has a stop of 8 ticks and a take profit of 20 ticks, if the parent is filled and I want to later modify the stop loss order(s) of the parent, I'm assuming that logic is on me to sort out finding the order_id of the child stop orders, taken from the exchange notification messages I get back?

**Comment by rundef** [comment]
Brackets orders are retrieved/updated for you automatically.

See the documentation: [Modifying an order](https://async-rithmic.readthedocs.io/en/latest/orders.html#modifying-an-order)
[Relevant code is here](https://github.com/rundef/async_rithmic/blob/main/async_rithmic/plants/order.py#L340-L371)

Please open new issues if you have further questions !
Thank you

**Comment by dominiontrading** [comment]
Hey rundef,
 
How difficult would it be for you to add something to the submit order method, another kwarg? If you submit a bracket order with STOP_MARKET entry (eg Long), if by the time your order reaches the exchange the price has moved, it will get Rejected, buy stop must be above current price.

Rithmic advised:

You may be interested in using the ‘stop_market_on_reject’ field in ‘request_bracket_order.proto’.

Setting it to True will convert stop orders to market orders if rejected.

Would be amazing if we can add to the library!
